# Copyright 2025 Pasteur Labs. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Tesseract API module for immersa_tesseract_inference_wake_observation
# Generated by tesseract 1.11.0 on 2026-08-05T22:43:17.254229

from typing import Any

import equinox as eqx
import jax
import jax.numpy as jnp
from pydantic import BaseModel, Field
from tesseract_core.runtime import Array, Differentiable, Float64
from tesseract_core.runtime.jax_recipes import (
    jax_abstract_eval,
    jax_apply,
    jax_jacobian,
    jax_jvp,
    jax_vjp,
)

#
# Schemata
#


class InputSchema(BaseModel):
    """Dense staggered wake velocity fields and sparse sensor locations."""

    ux: Differentiable[Array[(None, None, None), Float64]] = Field(
        description="Streamwise velocity field with shape (Nx_ux, Ny_ux, Nt)."
    )

    uy: Differentiable[Array[(None, None, None), Float64]] = Field(
        description="Cross-stream velocity field with shape (Nx_uy, Ny_uy, Nt)."
    )

    ux_x: Array[(None,), Float64] = Field(
        description="x coordinates of the ux staggered grid."
    )

    ux_y: Array[(None,), Float64] = Field(
        description="y coordinates of the ux staggered grid."
    )

    uy_x: Array[(None,), Float64] = Field(
        description="x coordinates of the uy staggered grid."
    )

    uy_y: Array[(None,), Float64] = Field(
        description="y coordinates of the uy staggered grid."
    )

    times: Array[(None,), Float64] = Field(
        description="Times corresponding to the velocity snapshots."
    )

    sensor_x: Differentiable[Array[(None,), Float64]] = Field(
        description="x coordinates of the wake sensors."
    )

    sensor_y: Differentiable[Array[(None,), Float64]] = Field(
        description="y coordinates of the wake sensors."
    )

    sensor_times: Array[(None,), Float64] = Field(
        description="Times at which the sensors are sampled."
    )


class OutputSchema(BaseModel):
    """Sparse wake velocity measurements."""

    measurements: Differentiable[Array[(None, None, 2), Float64]] = Field(
        description=(
            "Interpolated wake measurements with shape "
            "(N_sensors, N_times, 2), where the final dimension is [ux, uy]."
        )
    )


#
# Interpolation
#


def _trilinear_interpolate(
    field: jax.Array,
    x_grid: jax.Array,
    y_grid: jax.Array,
    t_grid: jax.Array,
    x: jax.Array,
    y: jax.Array,
    t: jax.Array,
) -> jax.Array:
    """Interpolate a field on a rectilinear x-y-time grid."""
    ix = jnp.searchsorted(x_grid, x, side="right") - 1
    iy = jnp.searchsorted(y_grid, y, side="right") - 1
    it = jnp.searchsorted(t_grid, t, side="right") - 1

    ix = jnp.clip(ix, 0, x_grid.shape[0] - 2)
    iy = jnp.clip(iy, 0, y_grid.shape[0] - 2)
    it = jnp.clip(it, 0, t_grid.shape[0] - 2)

    x0 = x_grid[ix]
    x1 = x_grid[ix + 1]

    y0 = y_grid[iy]
    y1 = y_grid[iy + 1]

    t0 = t_grid[it]
    t1 = t_grid[it + 1]

    wx = (x - x0) / (x1 - x0)
    wy = (y - y0) / (y1 - y0)
    wt = (t - t0) / (t1 - t0)

    f000 = field[ix, iy, it]
    f100 = field[ix + 1, iy, it]
    f010 = field[ix, iy + 1, it]
    f110 = field[ix + 1, iy + 1, it]

    f001 = field[ix, iy, it + 1]
    f101 = field[ix + 1, iy, it + 1]
    f011 = field[ix, iy + 1, it + 1]
    f111 = field[ix + 1, iy + 1, it + 1]

    f00 = (1.0 - wx) * f000 + wx * f100
    f10 = (1.0 - wx) * f010 + wx * f110

    f01 = (1.0 - wx) * f001 + wx * f101
    f11 = (1.0 - wx) * f011 + wx * f111

    f0 = (1.0 - wy) * f00 + wy * f10
    f1 = (1.0 - wy) * f01 + wy * f11

    return (1.0 - wt) * f0 + wt * f1


#
# Required endpoint
#


@eqx.filter_jit
def apply_jit(inputs: dict) -> dict:
    """Sample the staggered wake velocity fields at sparse sensors."""
    ux = inputs["ux"]
    uy = inputs["uy"]

    ux_x = inputs["ux_x"]
    ux_y = inputs["ux_y"]

    uy_x = inputs["uy_x"]
    uy_y = inputs["uy_y"]

    times = inputs["times"]

    sensor_x = inputs["sensor_x"]
    sensor_y = inputs["sensor_y"]
    sensor_times = inputs["sensor_times"]

    def sample_one_sensor(
        x: jax.Array,
        y: jax.Array,
    ) -> jax.Array:
        def sample_one_time(t: jax.Array) -> jax.Array:
            ux_obs = _trilinear_interpolate(
                ux,
                ux_x,
                ux_y,
                times,
                x,
                y,
                t,
            )

            uy_obs = _trilinear_interpolate(
                uy,
                uy_x,
                uy_y,
                times,
                x,
                y,
                t,
            )

            return jnp.stack((ux_obs, uy_obs))

        return jax.vmap(sample_one_time)(sensor_times)

    measurements = jax.vmap(sample_one_sensor)(
        sensor_x,
        sensor_y,
    )

    return {"measurements": measurements}


def apply(inputs: InputSchema) -> OutputSchema:
    """Evaluate the sparse wake observation operator."""
    out = jax_apply(apply_jit, inputs)
    return OutputSchema(**out)


#
# JAX-handled gradient endpoints (no need to modify)
#


def jacobian(
    inputs: InputSchema,
    jac_inputs: set[str],
    jac_outputs: set[str],
) -> dict[str, dict[str, Any]]:
    """Full Jacobian of the requested outputs w.r.t. the requested inputs."""
    return jax_jacobian(apply_jit, inputs, jac_inputs, jac_outputs)


def jacobian_vector_product(
    inputs: InputSchema,
    jvp_inputs: set[str],
    jvp_outputs: set[str],
    tangent_vector: dict[str, Any],
) -> dict[str, Any]:
    """Forward-mode directional derivative along ``tangent_vector``."""
    return jax_jvp(apply_jit, inputs, jvp_inputs, jvp_outputs, tangent_vector)


def vector_jacobian_product(
    inputs: InputSchema,
    vjp_inputs: set[str],
    vjp_outputs: set[str],
    cotangent_vector: dict[str, Any],
) -> dict[str, Any]:
    """Reverse-mode pullback of ``cotangent_vector`` onto the inputs."""
    return jax_vjp(apply_jit, inputs, vjp_inputs, vjp_outputs, cotangent_vector)


def abstract_eval(abstract_inputs: Any) -> dict:
    """Infer output shapes and dtypes without running the computation."""
    return jax_abstract_eval(apply_jit, abstract_inputs)
