[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "immersa_tesseract_inference_shared"
version = "0.1.0"
description = "Shared code for Immersa Tesseract Inference tesseracts"
authors = [{ name = "Arturo Machado Burgos" }]
requires-python = ">=3.10"
dependencies = [
    # Add dependencies here
]

[tool.setuptools.packages.find]
where = ["."]
include = ["immersa_tesseract_inference_shared", "immersa_tesseract_inference_shared.*"]
