# Copyright 2025 Pasteur Labs. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Tesseract API module for immersa_tesseract_inference_immersa_forward
# Generated by tesseract 1.11.0 on 2026-08-05T22:42:55.960032


from pathlib import Path

import numpy as np
from juliacall import Main as jl
from pydantic import BaseModel
from tesseract_core.runtime import Array, Float64

#
# Julia setup
#

_here = Path(__file__).parent
jl.include(str(_here / "julia" / "src" / "ImmersaForward.jl"))


#
# Schemas
#


class InputSchema(BaseModel):
    """Angle of attack and numerical parameters for the Immersa forward solver."""

    angle_of_attack_deg: Float64

    h: Float64 = 0.1
    dt: Float64 = 0.005
    tf: Float64 = 1.0
    Re: Float64 = 200.0

    snapshot_freq: int = 20


class OutputSchema(BaseModel):
    """Velocity history produced by flow past a fixed flat plate."""

    ux: Array[(None, None, None), Float64]
    uy: Array[(None, None, None), Float64]

    ux_x: Array[(None,), Float64]
    ux_y: Array[(None,), Float64]

    uy_x: Array[(None,), Float64]
    uy_y: Array[(None,), Float64]

    times: Array[(None,), Float64]

    angle_of_attack_deg: Float64

    plate_length: Float64
    mid_chord_x: Float64
    mid_chord_y: Float64

    n_ib: int
    ds: Float64


#
# Required endpoints
#


def apply(inputs: InputSchema) -> OutputSchema:
    """Run flow past a fixed flat plate at the requested angle of attack."""
    result = jl.ImmersaForward.run_forward(
        float(inputs.angle_of_attack_deg),
        h=float(inputs.h),
        dt=float(inputs.dt),
        tf=float(inputs.tf),
        Re=float(inputs.Re),
        snapshot_freq=int(inputs.snapshot_freq),
    )

    return OutputSchema(
        ux=np.asarray(result.ux, dtype=np.float64),
        uy=np.asarray(result.uy, dtype=np.float64),
        ux_x=np.asarray(result.ux_x, dtype=np.float64),
        ux_y=np.asarray(result.ux_y, dtype=np.float64),
        uy_x=np.asarray(result.uy_x, dtype=np.float64),
        uy_y=np.asarray(result.uy_y, dtype=np.float64),
        times=np.asarray(result.times, dtype=np.float64),
        angle_of_attack_deg=float(result.angle_of_attack_deg),
        plate_length=float(result.plate_length),
        mid_chord_x=float(result.mid_chord_x),
        mid_chord_y=float(result.mid_chord_y),
        n_ib=int(result.n_ib),
        ds=float(result.ds),
    )


#
# Optional endpoints
#

# import numpy as np

# def jacobian(inputs: InputSchema, jac_inputs: set[str], jac_outputs: set[str]):
#     return {}

# def jacobian_vector_product(
#     inputs: InputSchema,
#     jvp_inputs: set[str],
#     jvp_outputs: set[str],
#     tangent_vector: dict[str, np.typing.ArrayLike]
# ) -> dict[str, np.typing.ArrayLike]:
#     return {}

# def vector_jacobian_product(
#     inputs: InputSchema,
#     vjp_inputs: set[str],
#     vjp_outputs: set[str],
#     cotangent_vector: dict[str, np.typing.ArrayLike]
# ) -> dict[str, np.typing.ArrayLike]:
#     return {}

# def abstract_eval(abstract_inputs):
#     return {}
