# Copyright 2025 Pasteur Labs. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Tesseract API module for immersa_tesseract_inference_immersa_forward
# Generated by tesseract 1.11.0 on 2026-08-05T22:42:55.960032


from pydantic import BaseModel

#
# Schemas
#


class InputSchema(BaseModel):
    """Geometry parameters describing the immersed body."""


class OutputSchema(BaseModel):
    """Downstream wake velocity history produced by the simulation."""


#
# Required endpoints
#


def apply(inputs: InputSchema) -> OutputSchema:
    """Run the immersed-boundary simulation for the given geometry."""
    return OutputSchema()


#
# Optional endpoints
#

# import numpy as np

# def jacobian(inputs: InputSchema, jac_inputs: set[str], jac_outputs: set[str]):
#     return {}

# def jacobian_vector_product(
#     inputs: InputSchema,
#     jvp_inputs: set[str],
#     jvp_outputs: set[str],
#     tangent_vector: dict[str, np.typing.ArrayLike]
# ) -> dict[str, np.typing.ArrayLike]:
#     return {}

# def vector_jacobian_product(
#     inputs: InputSchema,
#     vjp_inputs: set[str],
#     vjp_outputs: set[str],
#     cotangent_vector: dict[str, np.typing.ArrayLike]
# ) -> dict[str, np.typing.ArrayLike]:
#     return {}

# def abstract_eval(abstract_inputs):
#     return {}
