# Copyright 2025 Pasteur Labs. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Tesseract API module for immersa_tesseract_inference_wake_surrogate
# Generated by tesseract 1.11.0 on 2026-08-22T07:24:18.648539
# Modified to implement the frozen V4 WakeSurrogate model.

"""Differentiable WakeSurrogate Tesseract.

Frozen V4 surrogate for sparse wake measurements behind a flat plate.

Inputs
------
angle_of_attack_deg:
    Plate angle of attack in degrees.

sensor_x, sensor_y:
    Coordinates of arbitrary sparse wake sensors.

Outputs
-------
measurements:
    Predicted [ux, uy] at the five fixed observation times
    [12.0, 13.3, 15.1, 17.4, 20.0].

    Shape:
        (N_sensors, 5, 2)
"""

from pathlib import Path
from typing import Any

import equinox as eqx
import jax
import jax.numpy as jnp
import numpy as np
from pydantic import BaseModel, Field
from tesseract_core.runtime import Array, Differentiable, Float32
from tesseract_core.runtime.jax_recipes import (
    jax_abstract_eval,
    jax_apply,
    jax_jacobian,
    jax_jvp,
    jax_vjp,
)

# ============================================================
# Fixed V4 configuration
# ============================================================

WIDTH = 128
DEPTH = 3

FOURIER_FREQUENCIES = jnp.array(
    [1.0, 2.0, 4.0, 8.0],
    dtype=jnp.float32,
)


# ============================================================
# Schemas
# ============================================================


class InputSchema(BaseModel):
    """AoA and sparse wake sensor locations."""

    angle_of_attack_deg: Differentiable[Float32] = Field(
        description=(
            "Flat-plate angle of attack in degrees. "
            "The surrogate was trained over 0 to 90 degrees."
        )
    )

    sensor_x: Differentiable[Array[(None,), Float32]] = Field(
        description=(
            "x coordinates of the wake sensors. Training/design region is 1 <= x <= 3."
        )
    )

    sensor_y: Differentiable[Array[(None,), Float32]] = Field(
        description=(
            "y coordinates of the wake sensors. Training/design region is -1 <= y <= 1."
        )
    )


class OutputSchema(BaseModel):
    """Surrogate sparse wake measurements."""

    measurements: Differentiable[Array[(None, 5, 2), Float32]] = Field(
        description=(
            "Predicted wake measurements with shape "
            "(N_sensors, 5, 2). "
            "The final dimension is [ux, uy]. "
            "The five fixed observation times are "
            "[12.0, 13.3, 15.1, 17.4, 20.0]."
        )
    )


# ============================================================
# Frozen V4 network
# ============================================================


class WakeSurrogate(eqx.Module):
    """Frozen V4 neural wake surrogate."""

    mlp: eqx.nn.MLP

    def __init__(
        self,
        key: jax.Array,
    ) -> None:
        n_original = 3

        # Fourier features are applied only to x and y.
        n_spatial = 2

        n_fourier = 2 * n_spatial * len(FOURIER_FREQUENCIES)

        feature_size = n_original + n_fourier

        self.mlp = eqx.nn.MLP(
            in_size=feature_size,
            out_size=10,
            width_size=WIDTH,
            depth=DEPTH,
            activation=jax.nn.silu,
            final_activation=lambda x: x,
            key=key,
        )

    def fourier_features(
        self,
        inputs: jax.Array,
    ) -> jax.Array:
        """Add Fourier features to normalized x and y only."""
        spatial = inputs[1:]

        angles = jnp.pi * spatial[:, None] * FOURIER_FREQUENCIES[None, :]

        return jnp.concatenate(
            [
                inputs,
                jnp.sin(angles).reshape(-1),
                jnp.cos(angles).reshape(-1),
            ]
        )

    def __call__(
        self,
        inputs: jax.Array,
    ) -> jax.Array:
        """Predict ten standardized velocity outputs."""
        features = self.fourier_features(inputs)

        return self.mlp(features)


# ============================================================
# Load frozen artifacts
# ============================================================

_THIS_DIR = Path(__file__).resolve().parent

_MODEL_FILE = _THIS_DIR / "best_model.eqx"

_NORMALIZATION_FILE = _THIS_DIR / "normalization.npz"


def _load_frozen_model() -> WakeSurrogate:
    """Construct the V4 architecture and load frozen weights."""
    model = WakeSurrogate(jax.random.PRNGKey(0))

    return eqx.tree_deserialise_leaves(
        _MODEL_FILE,
        model,
    )


def _load_normalization() -> tuple[jax.Array, jax.Array]:
    """Load training-only output normalization statistics."""
    with np.load(_NORMALIZATION_FILE) as data:
        y_mean = jnp.asarray(
            data["y_mean"].reshape(-1),
            dtype=jnp.float32,
        )

        y_std = jnp.asarray(
            data["y_std"].reshape(-1),
            dtype=jnp.float32,
        )

    return (
        y_mean,
        y_std,
    )


_MODEL = _load_frozen_model()

_Y_MEAN, _Y_STD = _load_normalization()


# ============================================================
# Surrogate evaluation
# ============================================================


def _predict_one_sensor(
    angle_of_attack_deg: jax.Array,
    x: jax.Array,
    y: jax.Array,
) -> jax.Array:
    """Predict the five-time wake history at one sensor."""
    # --------------------------------------------------------
    # Physical -> normalized inputs
    # --------------------------------------------------------

    alpha_normalized = 2.0 * angle_of_attack_deg / 90.0 - 1.0

    x_normalized = x - 2.0

    y_normalized = y

    normalized_input = jnp.stack(
        [
            alpha_normalized,
            x_normalized,
            y_normalized,
        ]
    )

    # --------------------------------------------------------
    # Frozen neural surrogate
    # --------------------------------------------------------

    prediction_normalized = _MODEL(normalized_input)

    # --------------------------------------------------------
    # Standardized -> physical velocity
    # --------------------------------------------------------

    prediction_physical = prediction_normalized * _Y_STD + _Y_MEAN

    # The network output is:
    #
    # [ux(t1), uy(t1), ..., ux(t5), uy(t5)]
    #
    # where:
    #
    # [t1, t2, t3, t4, t5]
    # =
    # [12.0, 13.3, 15.1, 17.4, 20.0]
    #
    # Reshape to:
    #
    # (5, 2)

    return prediction_physical.reshape(
        5,
        2,
    )


# ============================================================
# Required endpoint
# ============================================================


@eqx.filter_jit
def apply_jit(
    inputs: dict,
) -> dict:
    """Predict sparse wake observations."""
    angle_of_attack_deg = inputs["angle_of_attack_deg"]

    sensor_x = inputs["sensor_x"]

    sensor_y = inputs["sensor_y"]

    measurements = jax.vmap(
        lambda x, y: _predict_one_sensor(
            angle_of_attack_deg,
            x,
            y,
        )
    )(
        sensor_x,
        sensor_y,
    )

    return {
        "measurements": measurements,
    }


def apply(
    inputs: InputSchema,
) -> OutputSchema:
    """Evaluate the frozen V4 WakeSurrogate."""
    out = jax_apply(
        apply_jit,
        inputs,
    )

    return OutputSchema(**out)


# ============================================================
# JAX-handled derivative endpoints
# ============================================================


def jacobian(
    inputs: InputSchema,
    jac_inputs: set[str],
    jac_outputs: set[str],
) -> dict[str, dict[str, Any]]:
    """Full Jacobian of requested outputs with respect to inputs."""
    return jax_jacobian(
        apply_jit,
        inputs,
        jac_inputs,
        jac_outputs,
    )


def jacobian_vector_product(
    inputs: InputSchema,
    jvp_inputs: set[str],
    jvp_outputs: set[str],
    tangent_vector: dict[str, Any],
) -> dict[str, Any]:
    """Forward-mode directional derivative."""
    return jax_jvp(
        apply_jit,
        inputs,
        jvp_inputs,
        jvp_outputs,
        tangent_vector,
    )


def vector_jacobian_product(
    inputs: InputSchema,
    vjp_inputs: set[str],
    vjp_outputs: set[str],
    cotangent_vector: dict[str, Any],
) -> dict[str, Any]:
    """Reverse-mode pullback."""
    return jax_vjp(
        apply_jit,
        inputs,
        vjp_inputs,
        vjp_outputs,
        cotangent_vector,
    )


def abstract_eval(
    abstract_inputs: Any,
) -> dict:
    """Infer output shapes and dtypes."""
    return jax_abstract_eval(
        apply_jit,
        abstract_inputs,
    )
